### ISSUE TITLE
Languages translation request

### ISSUE THREAD

**Issue by MineCommanderCN** [OpenNBS/OpenNoteBlockStudio#112]
**Is your feature request related to a problem? Please describe.**
I am a Chinese and I really like this project! But when I use it at the first time, I can't see any language settings! And I only can use it in English! The experience of that is so bad!

**Describe the enhancement you'd like**
JUST add a language setting and support Chinese, or more languages such as Japenese, French, German and so on.

**Others**
My English maybe is not very good, but this feature is really really important! So, please!

**Comment by Bentroen** [comment]
Language translations are a planned addition and will be worked on in the near future. That said, I'm not sure if it will be possible to add Chinese, due to it using a different charset that the engine we're using doesn't support. We'll see what can be done though. Thanks for your suggestion!

**Comment by Creepercdn** [comment]
> 
> 
> Language translations are a planned addition and will be worked on in the near future. That said, I'm not sure if it will be possible to add Chinese, due to it using a different charset that the engine we're using doesn't support. We'll see what can be done though. Thanks for your suggestion!

UTF-8.

**Comment by 8MiYile** [comment]
@Bentroen Please use UTF-8 ,this can support Chinese,and another language
thx

**Comment by chenxi050402** [comment]
> @Bentroen Please use UTF-8 ,this can support Chinese,and another language
> thx

I think GBK is better

**Comment by Creepercdn** [comment]
> > @Bentroen Please use UTF-8 ,this can support Chinese,and another language
> > thx
> 
> I think GBK is better

GBK is not support some Chinese word and many another language

**Comment by Bentroen** [comment]
Update from #112:

With the program as it currently stands, it's very difficult to implement translations in an elegant way (especially for languages with different writing systems such as Russian and Chinese). That said, we're currently in the process of rewriting the program from scratch in another engine (translations being one of many, many reasons). This new version will not only be fully translatable, but the strings will be uploaded to a translation platform so everyone can contribute. We aim to release this version in a few months if everything goes well (you can follow #4 for updates on this). :)

**Comment by LiuShaoYe-173** [comment]
Wow,That`s GREAT! I am AGREE!!

**Comment by chenxi050402** [comment]
Added Simplified Chinese support in 3.9.0.

**Comment by 8MiYile** [comment]
> Added Simplified Chinese support in 3.9.0.

Nice

**Comment by Encode42** [comment]
It's not released yet, you'll have to build it yourself or wait for the version to be released

**Comment by Bentroen** [comment]
Not resolved yet since it's still not possible to translate to other languages :)

**Comment by peulbong** [comment]
Korean
