### ISSUE TITLE
Text boxes don't properly register key presses sometimes

### ISSUE THREAD

**Issue by CensoredExtended** [OpenNBS/OpenNoteBlockStudio#123]
**Is your feature request related to a problem? Please describe.**

It kinda is related. In the old studio version this also was a issue.
When you want to edit the song properties the typing is so hard.
Most of the times it will not type in the fields when you type.

**Describe the enhancement you'd like**

I would love to see this finally getting fixed. And maybe improve the performance of the typing boxes.

**Additional context**

https://prnt.sc/qw4a51

**Comment by Bentroen** [comment]
As the engine we're using has no built-in input fields, the typing boxes were manually implemented using 600+ lines of code. I don't think there's a way to make them perform better, as they're tied to the performance of the program – if it slows down, the rate at which the boxes detect a key press will also slow down, and as such it may not register some key presses.

I'll see if we can find an alternative. For now, if it's too difficult to type anything, try typing what you want in an external text editor, then paste it into its respective box in the program.

**Comment by Archerfy** [comment]
Hey,

Thank you so much for the information you explained above.
I will use a notepadd to type the lines and copy & paste it than.

I appreciate the explanation.

**Comment by Bentroen** [comment]
Fixed by compiling with YYC (from 3.10.0-beta.3 onwards).
