### ISSUE TITLE
Installer creates start menu shortcuts only for admin user

### ISSUE THREAD

**Issue by kvibber** [OpenNBS/OpenNoteBlockStudio#127]
When installing NBS 3.7.1 into a Microsoft Family account profile on Windows 10, it defaults to the profile of the admin user running the installer. If you change it to point to the family user's profile, it does successfully install the application to their profile - but the start menu shortcuts are created in the admin user's profile instead.

**Comment by Bentroen** [comment]
Not sure there's much we can do about that. GameMaker is very limited in terms of what you can do "outside" the application.
