### ISSUE TITLE
Datapacks don't have volume/panning control

### ISSUE THREAD

**Issue by slippyHarrison** [OpenNBS/OpenNoteBlockStudio#165]
When creating songs that utilize panning and volume control on notes then exporting them in the form of a datapack, the notes are played at full volume with zero panning.

To recreate:
Change the panning or volume of individual notes in a song.
Export to datapack

Sample nbs: [https://drive.google.com/file/d/1FwjZ-xXMNRhyuxHKCaPJsoSNsfiTjBzt/view?usp=sharing](url)

**Comment by ShinkoNet** [comment]
Make sure you ticked off the "Nearby Listening" checkbox in the datapack export settings. That function ignores stereo and volume controls.
