### ISSUE TITLE
Feature Request: Comments

### ISSUE THREAD

**Issue by TrapinchO** [OpenNBS/OpenNoteBlockStudio#175]
**Is your feature request related to a problem? Please describe.**
There is a problem (especially with longer songs) when you lose track of where you are and need to find it from the beggining.

**Describe the enhancement you'd like**
Add little marker (like new "instrument") that would display text when hovered over with mouse. It would be completely skipped when exporting (like comments in program's code).

**Additional context**
none

**Comment by Bentroen** [comment]
Related to #122 (may be implemented similarly)

**Comment by Bentroen** [comment]
Duplicate of #122
