### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by yourizuring** [OpenNBS/OpenNoteBlockStudio#205]
**Describe the bug**
I have no sound when I start up Minecraft Note Block Studio. I had it yesterday, but now I don't have any sound.

**To Reproduce**
1. Start Note Block Studio
2. Either open an existing file or create a new one.
3. No sound.

**Expected behavior**
To be sound.

**Screenshots**
No screenshots provided.

**Comment by yourizuring** [comment]
how do you do that?

**Comment by wafflecoffee** [comment]
Open Settings and go to sound settings, there should be a slide for whether you want to enable/disable mono audio.

**Comment by yourizuring** [comment]
Alright.
It doesn't work; I even tried restarting the application, doesn't work as well.
Restarting the computer does not work as well.

**Comment by wafflecoffee** [comment]
Do other applications give this same behaviour? (E.g. open up a tab in your web browser of YouTube and try playing a video.)

**Comment by yourizuring** [comment]
No.

**Comment by yourizuring** [comment]
Changing from stereo to mono and back to stereo while restarting the program does not work.

**Comment by TCAtrevor** [comment]
I have this issue, but only when I have the audio output of my computer set to my Razer headphone, when it is set to my speakers NBS will output audio fine.
