### ISSUE TITLE
MIDI Input and Import is wrong

### ISSUE THREAD

**Issue by karl-police** [OpenNBS/OpenNoteBlockStudio#217]
The notes from the MIDI input and import from F#5 or maybe everything, is like all shifted down by 1.

**Comment by CubixL** [comment]
Weird. I use a MIDI keyboard too but that doesn't happen to me, even when importing MIDIs.
You could just select all the notes and then pitch them down a semitone, the notes should revert back to normal.

**Comment by karl-police** [comment]
> Weird. I use a MIDI keyboard too but that doesn't happen to me, even when importing MIDIs.
> You could just select all the notes and then pitch them down a semitone, the notes should revert back to normal.

true but they split when "F" starts, so imagine there being two split up channels and how complicated it can become

**Comment by karl-police** [comment]
Issue is here:

https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/cb8aa0212beb982f6a4a33337fa5ddd5533f745d/scripts/midi_input_set_key/midi_input_set_key.gml#L9

well that's one... idk why there are own ids but I think the actual midi ids should be used

**Comment by karl-police** [comment]
here is another one for the importer

https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/master/scripts/import_midi/import_midi.gml#L29

I kinda fixed the issue that the notes are being shifted down by debugging it and etc., but I believe there might be a few others, but that's maybe the piano only.

**Comment by karl-police** [comment]
I made this now aswell, since there wasn't a patch for it yet here for some reason.

https://github.com/HielkeMinecraft/OpenNoteBlockStudio/pull/227
