### ISSUE TITLE
3.9.1 Known Issues

### ISSUE THREAD

**Issue by chenxi050402** [OpenNBS/OpenNoteBlockStudio#264]
These issues are known and will be fixed in the next version:

- ~Data packs with a tempo that's not multiple of 0.25 are invalid and not loaded properly in-game. For now, please keep the tempo to steps of 0.25 when exporting data packs.~ (#275) Fixed in 3.9.2

- ~The program crashes when closing the tempo input box if it's empty.~ (#282) Fixed in 3.9.2

- ~Keyboard shortcuts stop working after you type in the tempo edit box. To fix this, click the box again and leave it **by clicking away instead of pressing Enter or Esc.**~ Fixed in 3.9.2

- A series of errors labeled "Win32 function failed: HRESULT..." pop up, seemingly at random. To stop this from happening, disable 'Transparency effects' under Settings > Preferences > Interface. See #273

- ~The program will crash on startup if your desktop wallpaper image is too big~ Fixed in 3.9.1
- ~The new "Tempo Tapper" window is displaying in the wrong language in some places~ Fixed in 3.9.1

If you experience the issues above, there's no need to open a new issue.

**Comment by chenxi050402** [comment]
If you are experiencing the wallpaper issue, here's how to temporarily fix it:

Delete or rename wallpaper.bat and Wallpaper.jpg in the program data folder.
The default program data folder is `C:\Users\[Username Here]\Minecraft Note Block Studio\Data\`

**Comment by Bentroen** [comment]
This problem was addressed in version 3.9.1. Updating should fix the issue automatically :)
