### ISSUE TITLE
Pattern files dragging and dropping

### ISSUE THREAD

**Issue by IoeCmcomc** [OpenNBS/OpenNoteBlockStudio#274]
**Is your feature request related to a problem? Please describe.**
Since we can drag and drop .nbs files from Explorer into the program, it would be great if we could do the same thing with pattern files (.nbp).

**Describe the enhancement you'd like**
When dropping a (vaild) .nbp file, the pattern should be placed at the cursor position instead of the start of the song. If possible, it'd be nice to have the ability to preview the pattern while dragging.

**Additional context**
None.

**Comment by Bentroen** [comment]
Added in 4bc466196a8f35b65d345bc64cd8bfe3f03affd9.
