### ISSUE TITLE
Generate from MIDI Fails

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [OpenNBS/OpenNoteBlockStudio#285]
# Describe the bug
Upon uploading a MIDI file to onbs, the application errors

# To Reproduce
1. Launch obns
2. From the startup dialog, click "Generate song out of MIDI file"
3. Select the attached [MIDI file](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/7421732/song.zip) (located within the provided zip due to GitHub not being able to accept MIDIs)
4. Error Should appear

# Expected behavior
MIDI should open within onbs without issue

# Additional context
Crash log:
```
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [255] out of range [128] - -1.midi_ins(101477,255)
at gml_Script_open_midi
############################################################################################
gml_Script_open_midi (line -1)
gml_Script_draw_window_greeting
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0 (line -1)
```
Version: 3.9.1 Win10

**Comment by cam39** [comment]
quand j'importe mon fichier midi et qu'il le converti il me le converti qu'avec un seul instrument (la harpe) sa me soule je vois plein de gent le faire est ils on 10000 instrument ses soulant .

**Comment by cam39** [comment]
When I import my midi file and it converts it, it only converts it with one instrument (the harp).
