### ISSUE TITLE
song size

### ISSUE THREAD

**Issue by hackerplayz124** [OpenNBS/OpenNoteBlockStudio#297]
the bug is that the file is too large for scamatics to work

![image](https://user-images.githubusercontent.com/85144999/146150568-2c0b37c7-d1f0-4829-892f-19f3fa320c6e.png)

**Comment by Encode42** [comment]
This is a bug with whatever client side/server side schematic mod you're running. It's not even a bug, just a configuration issue.

As the message states, you'll have to increase the maximum schematic size for the mod
