### ISSUE TITLE
This is a new error prompt when I export.

### ISSUE THREAD

**Issue by maidang2233** [OpenNBS/OpenNoteBlockStudio#298]
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [24] out of range [24] - -9.layervol(100273,24)
at gml_Script_dat_generate
############################################################################################
gml_Script_dat_generate (line -1)
gml_Script_datapack_export
gml_Script_draw_window_datapack_export
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0 (line -1)

**Comment by maidang2233** [comment]
I tried to export it, but I trishoweI tried to export it, but it didn't work. He showed that it had been exported, but I couldn't find out where he exported it. The path was correct.

**Comment by Bentroen** [comment]
Hello and thank you for reporting the issue! If you scroll down to the last layer of the song, does this crash still occur?

**Comment by maidang2233** [comment]
There is no such problem when I export after the playback is finished.

> 成员
> ### [<img alt="@Bentroen" width="20" height="20" src="https://avatars.githubusercontent.com/u/29354120?s=60&amp;u=fe5e7e6da98e193fe40f484f743404ec4d3da5af&amp;v=4">](/Bentroen) ** [本特朗](/Bentroen) ** 评论 [18小时前](#issuecomment-996206630)

**Comment by maidang2233** [comment]
> 您好，感谢您报告此问题！如果向下滚动到歌曲的最后一层，是否还会发生这种崩溃？

Still exported the file that could not be found, but he prompted that the export was successful.

**Comment by chenxi050402** [comment]
你保存的地有权限吗 换个应该有权限的文件夹保存？
现在还没法检测选择的文件夹的可用性

**Comment by maidang2233** [comment]
The problem has been sThe probhe softwTheftware in administrator mode, he can.I The problem has beon solved. When I open the software in administrator mode, it can be exported.

**Comment by maidang2233** [comment]
ThThe problem has been solved, and it can be exported when I run as an administrator.

**Comment by maidang2233** [comment]
> 你保存的地有权限吗换个应该有权限的文件夹保存？ 现在还没行业义法律检测选择的文件夹数的可用性 你用的什么文件试的可以的话教育传上来我试试能不能重现

看翻译吧
