### ISSUE TITLE
extra note block resourcepack doesn't download

### ISSUE THREAD

**Issue by HappyAlexRomania** [OpenNBS/OpenNoteBlockStudio#299]
**Describe the bug**
when I try to download the extra noteblock resourcepack, it says it saved succesfully, but it actually didn't save.

**To Reproduce**
1. Go to 'File\Export as data pack...'
2. turn on the 'include out-of-range notes'
3. click on the 'Get extra notes pack' button
4. click save and look for the zip in the path you saved the zip and you'll se that it isn't there

**Expected behavior**
The resourcepack should be exported.

**Comment by Bentroen** [comment]
Hi @chenxi050402, what's the commit that resolved this issue?

**Comment by chenxi050402** [comment]
> Hi @chenxi050402, what's the commit that resolved this issue?

I disabled filesystem sandboxing in ed4f4a5e9188ca49c9c1d83bc6e75f03d128546f and it fixed

**Comment by akii0008** [comment]
:wave: if you still need the resource pack, you can find it here on this repo: https://github.com/OpenNBS/OpenNoteBlockStudio/blob/master/datafiles/Data/extranotes.zip
