### ISSUE TITLE
note blocks only playing default sound in game

### ISSUE THREAD

**Issue by WaterL0gged** [OpenNBS/OpenNoteBlockStudio#301]
when I export my schematic into minecraft using Amulet (which is still in 1.17), all the note blocks play as if they were sitting on dirt until i destroy and replace the same block. i made this song in the previous version of note block studio and only just updated it today.

to reproduce:
-save song in previous version in note block studio as schematic
-upload into Amulet world editor
-save world
-load into world

please let me know if any files are needed. thank you!

**Comment by Bentroen** [comment]
Hi! Thank you for reporting the issue, but it is a duplicate of #29. For now, you have to either:

- use the '1.13+' export option, added in 3.9.0, which will export the song to a `.nbt` file so you can load it into a structure block; or
- export a schematic using the '1.11-1.12' option, load it into a 1.12 world with MCEdit, then convert the world to a newer version.

We'll be working on updating the schematic export option to newer versions of Minecraft in the near future! Sorry for the inconvenience.

**Comment by WaterL0gged** [comment]
its ok! thanks for the help

**Comment by WaterL0gged** [comment]
its ok! thanks for the help
