### ISSUE TITLE
I can't sign up

### ISSUE THREAD

**Issue by CVtamg11** [OpenNBS/OpenNoteBlockStudio#312]
so i just downloaded the app and i wanted to get some music but when i went on the site and clicked sign in on either github or google it let me to a wierd link which was still the website but a white screen with nothing.

**Comment by Bentroen** [comment]
Hello, thanks for reporting the issue!

The Songs section is currently disabled as we're moving to a different database. Sorry for the inconvenience!

For now, you can find songs to download in our [Discord server](https://discord.gg/w35BqQp).
