### ISSUE TITLE
Rainbow Update

### ISSUE THREAD

**Issue by CreeperPookie** [OpenNBS/OpenNoteBlockStudio#322]
**Describe the enhancement you'd like**
In a recent update, rainbow piano keys were added. While I realize that it was definitely a joke, for April Fool's day, I actually quite like the look of the rainbow keys. Although they do consume a lot of CPU usage, is there any chance that some of the Rainbow UI (noteblocks, piano keys, etc) could be re-enabled through a toggle switch in the setting in a future update? (I am aware of rainbow mode, but that doesn't effect many elements)
Thank you.

**Comment by Bentroen** [comment]
Glad you enjoyed the rainbow update :)
As you've stated, the rainbow theme was only meant as an April Fools joke, and there are currently no plans to add it permanently to NBS (even if it weren't for that, updating the screen colors every frame causes a huge performance impact, and was implemented in a very hacky way).
In the future, it might be possible to customize some aspects of the application's look via plugins. I'll keep your request in mind :)
