### ISSUE TITLE
How does one squish together a song so it plays the same when changing tempo?

### ISSUE THREAD

**Issue by Glowing0v3rlord** [OpenNBS/OpenNoteBlockStudio#326]
Hi, I imported a song and have completely fine-tuned it to work in minecraft except that the tempo is at 20 ticks per second as opposed to the maximum 10. However, my song doesn't have any notes on the even parts, meaning that I could technically squish it down and then change the tempo so that it plays at the same speed. However, I can't find an easy way to do this. Does anyone know?

**Comment by Bentroen** [comment]
You can select all notes (Ctrl + A), right-click the workspace and click 'Compress selection' :)
