### ISSUE TITLE
NBT file not working?

### ISSUE THREAD

**Issue by Glowing0v3rlord** [OpenNBS/OpenNoteBlockStudio#327]
Hi, I'm trying to use a structure block to paste my .nbt file into my minecraft world, but whenever I do, all the redstone blocks get destroyed for some reason. I put stone for both my circuitry and floor and oak planks for my walkway, so I don't know what the problem is. Can anyone help?

**Comment by chenxi050402** [comment]
Only stone is supported for the walkway, circuit, and floor blocks, and only the default instrument blocks are supported in the current version. It will be resolved in the upcoming version.

**Comment by Bentroen** [comment]
Fixed in bb17eb092ca9f20f152ed914a4a520586c61b47c
