### ISSUE TITLE
It's not like a bug, but the schematic file is still saved as an nbt file. What should I do? I want to do it on world edit, but I can't

### ISSUE THREAD

**Issue by peulbong** [OpenNBS/OpenNoteBlockStudio#329]
**![i am not](https://user-images.githubusercontent.com/105538007/168415634-d4d8c613-5c08-4bf0-8602-cfa4d80cf7f9.jpg)

**Comment by Encode42** [comment]
The `.nbt` format is for use with jigsaw blocks in modern Minecraft versions. If you want to export as a `.schematic`, you must select an older Minecraft version (1.12) in the schematic export settings.

Relevant FAQ from the Discord:

> **🇶 When I import a schematic into a 1.13+ world, all instruments are the same! How can I fix this?**
> The schematics generated by the program are incompatible with newer versions, starting in 1.13. This is due to major changes in how the note blocks are stored in the world, as well as changes to the schematic format, which now have the extension `.schem` rather than `.schematic`. Those changes will require a full rewrite of the schematic export feature, which is planned for version 4.0 that will be released soon.
> You can use a workaround to get schematics into later versions: create a world in 1.12, load the schematic with MCEdit or your preferred tool, then load the world in the newer version. All instruments, including the ones added in 1.14, will be preserved.
