### ISSUE TITLE
Crash on startup. (RESOLVED)

### ISSUE THREAD

**Issue by TotallyNormal-Human** [OpenNBS/OpenNoteBlockStudio#330]
It just crashes on start, I don't know why. 
![image](https://user-images.githubusercontent.com/105567971/168449680-05163cfe-9ea8-40b2-9c90-5aab8d61109d.png)
Is there a solution for this that I don't know if? If you need more info just ask, though I'm pretty sure you will need it.

**Comment by TotallyNormal-Human** [comment]
Version is all of them, even the newer releases, done on latest release but it works on every release I've tested so far.

**Comment by Encode42** [comment]
> ...try going to "%APPDATA%\Minecraft_Note_Block_Studio" (copying that into the file explorer) then open the "settings.ini" using notepad and add `acrylic="0"` in a new line under the `[preferences]` tab

> ...go to the program's data folder (`C:\Users\<username>\Minecraft Note Block Studio\Data`), ... try deleting both `Wallpaper` files

Two solutions from the Discord server

**Comment by TotallyNormal-Human** [comment]
That first one fixed it, thank you for that. Sorry for wasting the time of everyone who read this.

**Comment by Encode42** [comment]
You can close the issue if it's resolved
![image](https://user-images.githubusercontent.com/34699884/168517630-bed62f41-554f-424c-bafe-7dff629ed861.png)
