### ISSUE TITLE
Export schematic generating a straight note block track

### ISSUE THREAD

**Issue by Yexiaowei11** [OpenNBS/OpenNoteBlockStudio#336]
Export the schematic to generate a straight note block track

**Comment by Yexiaowei11** [comment]
几条笔直的音符盒轨道

**Comment by chenxi050402** [comment]
Coincidentally this feature has just been made and is planned to be released in the upcoming version

**Comment by Yexiaowei11** [comment]
> 巧合的是，这个功能刚刚制作完成，并计划在即将发布的版本中发布

草中文不会说？

**Comment by chenxi050402** [comment]
> > 巧合的是，这个功能刚刚制作完成，并计划在即将发布的版本中发布
> 
> 草中文不会说？

这不是让其他人也看懂嘛（

**Comment by portal-draakje** [comment]
generate song out of 'midi' file is a fun idea but that file is almost never used for anything, can you make it also possible to generate song out of 'mp3'???

**Comment by Encode42** [comment]
@portal-draakje 

> MIDI files stores precise instructions on how the computer should play a song: what notes it should play, for how long each note should be played, and what instrument they must sound like. MP3, on the other hand, only stores sound waves. And no tool can look at them and figure out which notes are being played at what time, much less what instrument it's using, so that it can send the correct instructions to the computer. All MP3 to MIDI tools you can find online simply look at what frequencies are being played in a given moment and tells the computer to _press all those keys_. So, although it will mimic the sound waves as close as possible using only MIDI events, musically speaking it will sound _awful_. Again, listening to the song and transcribing it by manually placing all the notes will always give you the best results.

\- From the FAQ

Also, for future reference, this should be a new issue. The original issue is not related to MP3 nor import.

**Comment by portal-draakje** [comment]
ok, thanks for the information.
