### ISSUE TITLE
The pitch of custom instruments doesn't have effect when song is exported

### ISSUE THREAD

**Issue by MineCommanderCN** [OpenNBS/OpenNoteBlockStudio#337]
**Describe the bug**
音色设置中如果给自定义音色设置了非默认（F#4）的音调，那么当歌曲导出成音频时软件仍然会把它当作F#4处理，然后对应音色的部分就会变成一团糟

**To Reproduce**
1.添加一个自定义音色
2.在歌曲中放置这个自定义音色的音符，试听
3.在音色设置中更改自定义音色的音调
4.回到歌曲，试听可以发现音符的音调发生变化
5.文件->导出为MP3，试听导出后的音频，发现和修改音调前听起来一致

**Expected behavior**

**Screenshots**
一段视频：
https://user-images.githubusercontent.com/59791306/175285759-88125802-56ac-449d-b31e-65cb3886ac51.mp4

**Additional context**
版本：3.10.0-beta2

**Comment by chenxi050402** [comment]
It's a known issue of nbswave that you can check [here](https://github.com/Bentroen/nbswave/issues/4) and it's planned to be fixed in future versions.

**Comment by Bentroen** [comment]
Fixed in 82c962b87ea6e8bb3f4383120543f93cf201bf1b
