### ISSUE TITLE
Flashing dots while soloing a layer

### ISSUE THREAD

**Issue by LaptisMinecraft** [OpenNBS/OpenNoteBlockStudio#338]
**Describe the bug**
在使一层独奏的时候，在剩下的层上会有一层灰色的覆盖层
在这个灰色的覆盖层上会随机出现各种颜色的小点
我用的是2560x1440的屏幕，不知道是不是与DPI有关
（应该是渲染错误，我的屏幕没问题）

**To Reproduce**
1. 打开任意nbs文件
2. 使一层独奏
3. 将窗口全屏

**Expected behavior**
应该会看到很多在其它静音层上的小点

**Screenshots**
很难截图到
我稍后可能会上传一个视频说明

**Comment by chenxi050402** [comment]
目前还没法复现，你屏幕缩放设置是设的多少？

**Comment by chenxi050402** [comment]
要不你上传个视频吧看看什么效果的

**Comment by LaptisMinecraft** [comment]
https://wwu.lanzouy.com/ifZc307k6mri

**Comment by chenxi050402** [comment]
看起来不像软件的问题，你更新显卡驱动试试？
