### ISSUE TITLE
When attempting to download extra notes resource pack, no such file is saved.

### ISSUE THREAD

**Issue by spiceminecraft** [OpenNBS/OpenNoteBlockStudio#343]
**Describe the bug**
When attempting to download extra notes resource pack, no such file is saved to my computer.

**To Reproduce**
1. Go to File
2. Export as datapack
3. Click to "get extra notes pack"
4. Select location to save resource pack
5. Check location (in my case, downloads folder)
6. There is no saved resource pack to be found

**Expected behavior**
I expected to recieve the extra notes resource pack, but instead nothing was downloaded.

**Comment by chenxi050402** [comment]
Duplicate of #299
