### ISSUE TITLE
Can't import MIDI files because "Index Out Of Range"

### ISSUE THREAD

**Issue by Divine-101** [OpenNBS/OpenNoteBlockStudio#350]
Whenever I try to import a midi file, I get this error:

############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

Push :: Execution Error - Variable Index [255] out of range [128] - -1.midi_ins(100572,255)
at gml_Script_open_midi
############################################################################################
gml_Script_open_midi (line -1)
gml_Script_menu_click
gml_Script_menu_draw
gml_Object_obj_menu_Draw_0

Any idea how to fix this?

**Comment by chenxi050402** [comment]
Duplicate of #285
