### ISSUE TITLE
Open Minecraft Note Block Studio Deletes Itself On Startup

### ISSUE THREAD

**Issue by ZSolar1** [OpenNBS/OpenNoteBlockStudio#353]
So I was making a song and I pressed the play button to see how it sounded. as soon as it got to playing my custom .nbp file, the window just closed. I saved it a few mins ago so I thought I could keep going where I left off. I went to open the desktop shortcut, but it wasn't there. I knew that wasn't right so I clicked its icon on the taskbar. This showed up.

![Windows 8_25_2022 6_17_48 PM](https://user-images.githubusercontent.com/101154324/186778549-ee7553e9-ac6c-484b-97db-d50edb770607.png)

I knew that wasn't right, so I looked for its folder where the .exe is stored and it was still there. I had no idea what could have happened, so I entered the folder to see that it's .exe was gone and I don't know how to restore that so I just reinstalled it. I tried to open the new reinstalled version through my desktop shortcut. I waited a little bit, then the desktop shortcut just vanished. I checked if it's .exe was still there, but it had also vanished. Does anyone know how to fix this?

Here's a little info. I'm on windows 10. I used the Beta because when I used the latest 3.9 version, it comes up with this error.

![Code Error 8_24_2022 6_18_16 PM](https://user-images.githubusercontent.com/101154324/186779171-a242c3b9-7840-42aa-b578-a3d0ba0013e2.png)

I had installed the beta version in a custom directory. Also when I reinstalled it, I checked off the launch note block studio checkbox but it never launched.

If someone knows how to fix the issue when I open Open Note Block Studio 3.9.3, or the Issue when I open Open Note Block Studio 3.10.0 - beta.3, Please tell me how to fix both, or one.

**Comment by Bentroen** [comment]
Hi! Check your antivirus, it could be deleting the Note Block Studio executable when you try to run it.

**Comment by ZSolar1** [comment]
Windows Security has App & browser control off other then that i have no antivirus

**Comment by ZSolar1** [comment]
issue fixed through the discord server.
