### ISSUE TITLE
uninstall.exe flagged by antivirus

### ISSUE THREAD

**Issue by mercurialmusic** [OpenNBS/OpenNoteBlockStudio#354]
I'm afraid I don't have much information, but my Webroot antivirus flagged NBS's uninstall.exe as having/being malware after recently updating to [3.10.0-beta.3](https://github.com/OpenNBS/OpenNoteBlockStudio/releases/tag/v3.10.0-beta.3).

**Comment by Bentroen** [comment]
The uninstall executable is generated automatically by GameMaker, so if anything, it would be an issue on their end. Don't worry though, that's (most likely) a false positive!
