### ISSUE TITLE
3.33 t/s should be schematic compatible

### ISSUE THREAD

**Issue by miclol** [OpenNBS/OpenNoteBlockStudio#366]
**Feature Suggestion**
Since adding non-.25 increments of tempo, 3.33 t/s should now be perfectly fine to export as a schematic (3 tick repeaters between every noteblock)

**Comment by Bentroen** [comment]
Closing this as a duplicate of #29 since the schematic export redesign will make any tempo compatible (via odd-tick delay circuits and nearest-tick rounding).

###### Also, 3.33 t/s is such a _slow_ tempo as to be impractical to use 😅
