### ISSUE TITLE
Problem With My Keyboard/Midi Device

### ISSUE THREAD

**Issue by ACityOnGitHub** [OpenNBS/OpenNoteBlockStudio#374]
Hi. I have a problem with the midi device manager of the ONBS. I'm trying to record a song from my keyboard, and it does nothing. I've tried it with other music programs and it works well. I don't know why ONBS doesn't detect the input of the keys, but it detects my keyboard. I tried almost 10 times and still the same. I hope this problem gets solved soon.

Thanks!

**Comment by Bentroen** [comment]
Hi! First of all, do you see the name of the device in the lower-right corner of the status bar when you open NBS?

![image](https://user-images.githubusercontent.com/29354120/211696692-d4b10d34-325b-4464-bafc-d9edc63cb562.png)

If so, can you please try going to the Device Manager by clicking the following icon, and then making sure 'Use selected' (or any other instrument, for that matter) is selected?

![image](https://user-images.githubusercontent.com/29354120/211696203-8676fcd6-003c-40a9-90e5-86ce88f64bdf.png)

![image](https://user-images.githubusercontent.com/29354120/211696370-406c671e-87bd-443b-aeb6-551bb4cc9856.png)

Have you tried replugging your device, reopening and/or reinstalling NBS? Finally, what operating system are you using?
