### ISSUE TITLE
New format???

### ISSUE THREAD

**Issue by charlie-sans** [OpenNBS/OpenNoteBlockStudio#381]
hey. 
I am in the process of making a new file format
it's going to be ether  .VR or .VIRT
it will be built on the already existing version 5 format of the NBS files
 so there can be backward compatibility between my program and this one.
 
this is only a suggestion for the 4.0 update so you can take this as you will.

I have a python demo of the format for people to try so they can see how it works.

if you want I can comment with a GitHub repo containing the new format maker.

this format is licenced under the MIT licence, allowing it to be open source. 
I hope I can make it an open source of not then let me know!

**Comment by charlie-sans** [comment]
now i do want to let you know that this format will go thru heavy and extensive changes

**Comment by koca2000** [comment]
There was a discussion about the future of the .nbs format in #307.

**Comment by charlie-sans** [comment]
I have the base for it ready and can make the files and read/write to them. the problem is that I don't really know how Pynbs works. i did the things but it seams to be broken at the moment.

**Comment by Bentroen** [comment]
Hi! The new format you proposed is really interesting; however, since it's out of the scope for this project, I will be closing this issue for the moment. Feel free to suggest improvements to the existing format in #307, which is where we're tracking future additions to the current standard!
