### ISSUE TITLE
Suddenly Unable to open the app

### ISSUE THREAD

**Issue by atLancelot** [OpenNBS/OpenNoteBlockStudio#387]
I can no longer open ONBS. Yesterday it worked just fine, no issues. Installed it, started creating a song, saved went to bed. Today I go to open it and it tells me I no longer have permission to open the file. I uninstall but it tells me there is no uninstall file. I delete the ONBS files on my computer (except for the song files) and go to download it again. This time its telling me I don't have permission to save at this location- this location being the download folder, and to try again in the users folder. I then receive the same message. I updated and restarted my computer. Every time it starts back up it lets me download the file, but then deletes the file after trying to open the installer and telling me I do not have permission again. It doesn't let me download the file again until I've restarted my computer after that. I don't know if this is a problem with ONBS or my computer, but this issue has only ever occurred with this app.

**Comment by charlie-sans** [comment]
Your boot device. Ssd or hdd is dying and must have put itself into read only mode. That's my best guess and may not be accurate.

**Comment by atLancelot** [comment]
How would I go about checking that?

**Comment by atLancelot** [comment]
Another thing I should mention had had forgotten to mention is that I uninstalled a bunch of apps that were filling my C drive. I have 2 two terabyte drives, neither of which were completely full. My D drive has 1.19 terabytes of space left, so space shouldn't be an issue. I believe one of the apps I uninstalled was game maker, but after reading that I need that to use ONBS, I tried reinstalling that, to no avail.

**Comment by charlie-sans** [comment]
are you using the website version https://opennbs.org ?

or the game maker version from this github?

**Comment by charlie-sans** [comment]
> How would I go about checking that?

how long have you had these drives for?
and does the download bug just affect the installer of open nbs or more than that

**Comment by atLancelot** [comment]
I've had these drives for about two years, but should still be quite healthy.
I was able to download and open a mp3 file off of youtube, so I think the problem is exclusive to this app.

**Comment by atLancelot** [comment]
I downloaded it from the webite, but on that same page it says that you need game maker to open or edit a project. Theoretically, having game maker installed shouldn't interfere with onbs at all.

**Comment by charlie-sans** [comment]
that makes no sense. letting you download anything but onbs? hey @chenxi050402 can you help out here, even tho im a tech nerd i cant seem to figure this out

**Comment by atLancelot** [comment]
thanks for trying at least XD
i'd be happy to provide more info, i'd just need to know what to send

**Comment by atLancelot** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/56614578/228429122-b6acec7f-d58a-4019-8634-63bbb4c6b57d.png)
 this is the message i get

**Comment by atLancelot** [comment]
I'm the only person who uses this computer, I have admin, and this the only account on the pc

**Comment by chenxi050402** [comment]
can you check if windows defender have sandboxed the file or anything?

**Comment by atLancelot** [comment]
How would I go about that?

**Comment by charlie-sans** [comment]
> ![Screenshot (98)](https://user-images.githubusercontent.com/56614578/228429122-b6acec7f-d58a-4019-8634-63bbb4c6b57d.png)
>  this is the message i get

Did you get the zip file one or did you get the installer.

**Comment by chenxi050402** [comment]
click the windows defender tray icon at the bottom right of your screen and check the protection history

**Comment by atLancelot** [comment]
On the Open Note Block Studio website, I clicked download version 3.10.0
It prompted me to download Minecraft.Note.Block.Studio as an application. It seems once I try to download the file to a folder, it won't let me a second time, so I have to download it to a different one. Restarting the computer seems to let me download it to those folders again, but trying to open the file deletes them, though they aren't in my trashcan. 

To answer your question, it downloads an exe file. 

There is also no history in windows defender.
![Screenshot (99)](https://user-images.githubusercontent.com/56614578/228431529-ff0a9297-e35f-4917-ac11-b4e4af48a4ae.png)

**Comment by chenxi050402** [comment]
maybe try to download the zip instead of the installer on github?

**Comment by atLancelot** [comment]
I'll try that, give me a second

**Comment by atLancelot** [comment]
Welp... Whatever the issue was, that seemed to fix it. I'm now able to open the application! Thank you guys both so much!

**Comment by chenxi050402** [comment]
no problem!
