### ISSUE TITLE
Error opening

### ISSUE THREAD

**Issue by Emeralds1234** [OpenNBS/OpenNoteBlockStudio#388]
I can't open the it.

This will pop up when I open it

![RI~HXOG0E49M6}O)(~`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)

**Comment by chenxi050402** [comment]
Have you tried reinstalling or anything?

**Comment by Emeralds1234** [comment]
> 
Yes, I reinstalled it yesterday and just now

**Comment by Emeralds1234** [comment]
> 您是否尝试过重新安装或其他任何东西？

也许我能说中文？
昨天和刚才我都重装过一次，但没有用。
Yesterday and just now, I reinstalled it, but it didn't work.

**Comment by chenxi050402** [comment]
你看看你安装位置里data文件夹里有没有一个window.dll
有的话看看修改日期是不是和软件的exe修改日期一样

**Comment by Emeralds1234** [comment]
> 你看看你安装位置里data文件夹里有没有一个window.dll 有的话看看修改日期是不是和软件的exe修改日期一样

window.dll不在data里，一直是和exe文件放一起的
修改日期一样，不过exe.文件的修改时间晚3分钟

**Comment by chenxi050402** [comment]
那可能就是这个原因了 你把window.dll放到data里试试

**Comment by charlie-sans** [comment]
> I can't open the it.
> 
> This will pop up when I open it
> 
> ![RI~HXOG0E49M6}O)(~`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 

Do you have 32 bit on in gml. That's a resulting error from not having 32 bit on I think

**Comment by Emeralds1234** [comment]
> 你看你安装位置data文件夹里有没有一个window.dll 有的看修改日期不是和软件的exe修改日期一样

**Comment by Emeralds1234** [comment]
> > 你看你安装位置data文件夹里有没有一个window.dll有的看修改日期不是和软件的exe修改日期一样

**Comment by chenxi050402** [comment]
wat

**Comment by Emeralds1234** [comment]
> > I can't open the it.
> > This will pop up when I open it
> > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 
> Do you have 32 bit on in gml. That's a resulting error from not having 32 bit on I think



> 扫管笏

抱歉，还不是很会用这个论坛
window.dll文件并不在data里，而且我并没有找到它（中午的时候把date.win文件误认为window.dll了

**Comment by Emeralds1234** [comment]
> 扫管笔记

抱紧，还是不会很会用这个论坛
window.dll文件并不在data里，而我却没有找到它（中午的时候把date.win文件误认为是window.dll了

**Comment by Emeralds1234** [comment]
> 抱歉，还不是很会用这个论坛
> window.dll文件并不在data里，而我却没有找到它（中午的时候把date.win文件误认为是window.dll了

**Comment by Emeralds1234** [comment]
> > 我无法打开它。
> > 打开的时候会弹出这个
> > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 
> 你在 gml 中有 32 位吗？我认为这是由于没有 32 位而导致的错误

Sorry, I don't know where gml is

**Comment by Emeralds1234** [comment]
> > I can't open the it.
> > This will pop up when I open it
> > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 
> Do you have 32 bit on in gml. That's a resulting error from not having 32 bit on I think



> > 抱紧，还是不会很会用这个论坛
> > window.dll文件并不在data里，而我却没有找到它（中午的时候把date.win文件误认为是window.dll了



> 扫管笏

抱歉，我还不是很会用这个论坛
window.dll文件并不在data里，而我却没有找到它（中午的时候把date.win文件误认为是window.dll了

**Comment by Emeralds1234** [comment]
> > 我无法打开它。
> > 打开的时候会弹出这个
> > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 
> 你在 gml 中有 32 位吗？我认为这是由于没有 32 位而导致的错误

抱歉，我不知道 gml 在哪里

**Comment by Emeralds1234** [comment]
> 扫管笏

**Comment by Emeralds1234** [comment]
> > 我无法打开它。
> > 打开的时候会弹出这个
> > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> 
> 你在gml中有32位吗？我认为这是由于没有32位而导致的错误

Sorry，I don't now where is the gml

**Comment by chenxi050402** [comment]
> > > 我无法打开它。
> > > 打开的时候会弹出这个
> > > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> > 
> > 
> > 你在 gml 中有 32 位吗？我认为这是由于没有 32 位而导致的错误
> 
> 抱歉，我不知道 gml 在哪里

他之前用gamemaker打开工程的时候调错了报的这个错（
正常用户没有这个情况（
不用管（（

**Comment by Emeralds1234** [comment]
> > > > 我无法打开它。
> > > > 打开的时候会弹出这个
> > > > ![RIHXOG0E49M6}O)(`JH4C](https://user-images.githubusercontent.com/129254711/228437660-1e677027-af57-4109-91c2-a8de7b83b58a.png)
> > > 
> > > 
> > > 你在gml中有32位吗？我认为这是由于没有32位而导致的错误
> > 
> > 
> > 抱抱，我不知道gml在哪
> 
> 他之前用gamemaker打开工程的时候调错了报的这个错误（ 正常用户没有这个情况（ 不用管（（

emm 我不太会玩这个论坛（大哭

**Comment by Emeralds1234** [comment]
> 扫管笔记

data里面没有你说的文件，中午的时候我和另外一个文件弄混了
另外，之前我可以正常使用nbs的时候好像data里面也没有你说的那个文件

**Comment by Emeralds1234** [comment]
> 你下zip的然后解压到另一个文件夹试？

可以在哪里下zip的？

**Comment by chenxi050402** [comment]
在左上角code那里然后往下看有个releases

**Comment by Emeralds1234** [comment]
> 点左上角代号那里然后往下看有一个releases

看到了，我试试

**Comment by Emeralds1234** [comment]
> 你下zip的然后解压到另一个文件夹试试？

还是不行

**Comment by chenxi050402** [comment]
奇怪了 难道是被杀毒软件拦截了？

**Comment by Emeralds1234** [comment]
> 奇怪了 难道是被杀毒软件拦截了？

弹窗有显示拦截一个data.win的文件，不过我恢复了

**Comment by Emeralds1234** [comment]
> 要不你对比一下zip里面和软件文件夹罢 看看dll是不是都全

都全的

**Comment by chenxi050402** [comment]
嗯……

是只在现在这台电脑上有这个问题吗

**Comment by Emeralds1234** [comment]
> 嗯……
> 
> 是只在现在这台电脑上有这个问题吗

这个不知道，因为我只能用这一个电脑

**Comment by Emeralds1234** [comment]
> 嗯……
> 
> 是只在现在这台电脑上有这个问题吗

昨天中午我用完才出现的这个问题，然鹅昨天我并没有删里面的文件或是修改电脑上的东西

**Comment by chenxi050402** [comment]
啊这……
完全没有头猪了
你确定你安装的位置非管理员有读写的权限吗（属性里看

**Comment by Emeralds1234** [comment]
> 啊这…… 完全没有头猪了 你确定你安装的位置非管理员有读写的权限吗（属性里看

有的，因为我之前一直是可以用的

**Comment by Emeralds1234** [comment]
> 啊这…… 完全没有头猪了 你确定你安装的位置非管理员有读写的权限吗（属性里看

好吧，很奇怪的就好了，刚重装到另外一个文件夹，可以正常打开，不过装的几个还是不行

**Comment by chenxi050402** [comment]
那大概是权限或者盘的问题了

**Comment by Emeralds1234** [comment]
> 那大概是权限或者盘的问题了

可是我把新装的放到之前的文件夹里也能正常打开

**Comment by Emeralds1234** [comment]
> 那大概是权限或者盘的问题了

对了如果我还有一个不一样问题是要再发一篇吗

**Comment by chenxi050402** [comment]
> > 那大概是权限或者盘的问题了
> 
> 对了如果我还有一个不一样问题是要再发一篇吗

你可以再发 也可以在这里说

**Comment by chenxi050402** [comment]
是都无法导出还是只有这个工程无法导出？

**Comment by Emeralds1234** [comment]
> 那可能就是这个原因了你把window.dll放到data里试试

很抱歉又来麻烦你了
上次以后我这里又报错了好几次，但是重装就能修复，但过一段时间又会出现这个问题
今天我找到了原因，是因为杀毒软件将window.dll文件当成木马删掉了
但是每次我恢复window.dll文件后，再次点进NBS，杀毒软件又会再次将window.dll删掉，即使设置了不再查杀也没有作用，不知道怎样才能解决这个问题
