### ISSUE TITLE
note duration

### ISSUE THREAD

**Issue by Roundtable-Lee** [OpenNBS/OpenNoteBlockStudio#389]
Hello! The software is great, but I want to make a suggestion. 
When I was making songs using OpenNBS, I found that every single note had the same duration as the source timbre file. This may give unnatural feelings to the listeners. So if there is a function to change the note duration (to make quarter note, eighth note, etc.), the songs can be more tuneful. 
Although changing note duration is not possible in the game, but to some green hands it would be a useful function. Maybe you can do that by time stretching.

**Comment by Bentroen** [comment]
Hi, thanks for your suggestion!

As you mentioned yourself, there's no way to change the note duration in-game, so any sort of audio manipulation to achieve this wouldn't be easy to import into Minecraft. The closest we can get is simulating a sustain effect by repeating the same note multiple times, making them bounce left and right and adding a fade out. In the future, we'd also like to allow treating consecutive notes as a grouped entity, as to allow easier modification of the entire group of notes. This is currently being tracked in #294, so I'm going to close this issue as a duplicate. :)
