### ISSUE TITLE
I can't open the software

### ISSUE THREAD

**Issue by HaapsaluYT** [OpenNBS/OpenNoteBlockStudio#393]
**Describe the bug**
I can't open the software

**To Reproduce**
1. Clicking on the app. I have tried downloading the exe and the zip

**Expected behavior**
The app opening

**Screenshots**
Self-explanatory

**Comment by Emeralds1234** [comment]
Can you provide more explanation of the problem? I am referring to screenshots of software errors or other more specific explanations

**Comment by Bentroen** [comment]
> Can you provide more explanation of the problem? I am referring to screenshots of software errors or other more specific explanations
This would be very helpful, but generally speaking, running as administrator, restarting your system and/or updating your graphics drivers can fix the issue. You also need to have the MS Visual C++ redistributable, which is not installed automatically when you use a ZIP file. I recommend you uninstall NBS and run the installer (.exe) again. Hope this helps!

**Comment by Bentroen** [comment]
> Can you provide more explanation of the problem? I am referring to screenshots of software errors or other more specific explanations

This would be very helpful! But generally speaking, running as administrator, restarting your system and/or updating your graphics drivers can fix the issue. You also need to have the MS Visual C++ redistributable, which is not installed automatically when you use a ZIP file. I recommend you uninstall NBS and run the installer (.exe) again. Hope this helps!

**Comment by macks2008** [comment]
> Screenshots:
> self-explanatory
It really isn't. To quote [a favorite article of mine about reporting bugs effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html). 
> "It doesn't work"
> Give the programmer some credit for basic intelligence: if the program really didn't work at all, they would probably have noticed. Since they haven't noticed, it must be working for them. Therefore, either you are doing something differently from them, or your environment is different from theirs. They need information; providing this information is the purpose of a bug report. More information is almost always better than less.
