### ISSUE TITLE
Now the audio sound generated by the software is very messy, but because he counted the echo or something, I hope to fix this bug, otherwise I can't play an audio normally

### ISSUE THREAD

**Issue by BanZangdod** [OpenNBS/OpenNoteBlockStudio#414]
**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Additional context**

**Comment by BanZangdod** [comment]
Now the audio sound generated by the software is very messy, but because he counted the echo or something, I hope to fix this bug, otherwise I can't play an audio normally

**Comment by Bentroen** [comment]
Hi! I'm not sure I understand what the issue is. Would you mind describing it more clearly? Is it related to the audio export feature or the song playback in the NBS editor itself?
