### ISSUE TITLE
more support.

### ISSUE THREAD

**Issue by louden-preble** [OpenNBS/OpenNoteBlockStudio#422]
Hey dev's, is there a way where you can make a portable .exe file so that Open Note Block Studio so that it can work with wine?
(basically adding support for Linux and MacOS)

**Comment by encode42** [comment]
OpenNBS's installer already works with Wine on Linux, tested on Debian 10 and Arch.

You're also able to [download releases as a zip](https://github.com/OpenNBS/OpenNoteBlockStudio/releases/download/v3.10.0/Minecraft.Note.Block.Studio.zip).
