### ISSUE TITLE
a random crash and now im unable to use onnbs

### ISSUE THREAD

**Issue by liamwerk7676** [OpenNBS/OpenNoteBlockStudio#430]
**Describe the bug**
I have actualy no idea why this is happening but when i start open nnbs i get this error 
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_controller:

Illegal Buffer Index -1############################################################################################
gml_Script_instrument_load (line 22)
gml_Script_control_create (line 477)
gml_Object_obj_controller_Create_0 (line 0)

1. change some settings
2. restart
3. crash

**Expected behavior**
starts normaly

**Screenshots**
![image](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/112199156/5d97d242-8275-431a-aea0-818cbce277c4)

**Additional context**
__ Minecraft Note Block Studio log __
13:48:53 version: 3.10.0
13:48:53 version_date: 2022.10.01
13:48:53 gm_runtime_version: 2022.6.1.40
13:48:53 YYC: 1
13:48:53 working_directory: C:\ProgramData\chocolatey\lib\opennbs\tools\
13:48:53 file_directory: C:\Users\***\AppData\Roaming\Minecraft_Note_Block_Studio\
13:48:53 OS: Windows
13:48:53 os_version: 655360
13:48:53 os_is_network_connected: 1
13:48:53 os_get_language: nl
13:48:53 os_get_region: NL
13:48:53 USERDOMAIN: ****-ULTRA-PC
13:48:53 USERNAME: ***
13:48:53 USERPROFILE: C:\Users\***
13:48:53 APPDATA: C:\Users\***\AppData\Roaming
13:48:53 NUMBER_OF_PROCESSORS: 16
13:48:53 PROCESSOR_ARCHITECTURE: x86
13:48:53 PROCESSOR_IDENTFIER: 
13:48:53 PROCESSOR_LEVEL: 25
13:48:53 PROCESSOR_REVISION: 7401
13:48:53 Init libraries
13:48:53 File: C:\ProgramData\chocolatey\lib\opennbs\tools\Data\file.dll
13:48:53 Audio: C:\ProgramData\chocolatey\lib\opennbs\tools\Data\file.dll
13:48:53 audio_init
13:48:53 audio_file_decode
13:48:53 audio_start
13:48:53 audio_file_add
13:48:53 audio_sound_add
13:48:53 audio_combine
13:48:53 Init audio
13:48:53 Window: C:\ProgramData\chocolatey\lib\opennbs\tools\Data\window.dll
13:48:53 Midi input: C:\ProgramData\chocolatey\lib\opennbs\tools\Data\midiinput.dll
13:48:53 Libraries loaded
13:48:53 Load instrument: C:\ProgramData\chocolatey\lib\opennbs\tools\Data\Sounds\UI\metronome_click.ogg
13:48:53 audio_file_decode
13:48:53 buffer_load

**Comment by liamwerk7676** [comment]
oh yeah and i installed it from chocolatey

**Comment by chenxi050402** [comment]
The sound file loading process involves creating a temp file which may not be properly generated when running under chocolatey. We don't recommend installing using something like chocolatey as it may introduce restrictions on areas ONBS need to work with.

**Comment by liamwerk7676** [comment]
ok ill uninstall and then install from the website

**Comment by liamwerk7676** [comment]
it works now
