### ISSUE TITLE
Software not saved

### ISSUE THREAD

**Issue by cycian** [OpenNBS/OpenNoteBlockStudio#434]
So I downloaded the Minecraft note block studio software, I launched it after downloading. However, the software does not create a short cut even though I ticked the box create a short cut on my desktop.
1. Download the software
2. Tick the box create a short cut on my desktop
3. Wait for it to download
4. No short cut created on desktop
I supposed that it should help me create I short cut on my desktop, right?

**Comment by Bentroen** [comment]
Related: https://github.com/OpenNBS/OpenNoteBlockStudio/issues/127

**Comment by Bentroen** [comment]
Duplicate of #127
