### ISSUE TITLE
Error loading MIDI file:

### ISSUE THREAD

**Issue by NandukYT** [OpenNBS/OpenNoteBlockStudio#447]
the first message that pops up when i try to import the midi file is:
Error loading MIDI file:

First 4 bytes must be MThd

Continue anyway?
Yes No
![obraz](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/115937529/29c71ee9-7f81-4af8-989f-fcab589edcdd)

then i click yes and then i cant even continue, that what pops up:

Error loading MIDI file:

Header size must be 00 00 00 06

![obraz](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/115937529/98029c44-1a08-4154-8f9c-70ed3195030c)

just tried to import funky town to minecraft

**Comment by chenxi050402** [comment]
It means it's an invalid or corrupted midi file, can you upload the file here for inspection?

**Comment by NandukYT** [comment]
@chenxi050402 sure! Here it is: https://mega.nz/file/OGJWyQQT#MZ8z_283DosPAUJEq4iaH9IZgZm5AgIPhoutyW6GiuQ

**Comment by chenxi050402** [comment]
bruh it's an mp3 file
use an actual midi file plz
you can find them on midishow.com/en or just search
