### ISSUE TITLE
"OPEN SOURCE NOTE BLOCK EDITOR"

### ISSUE THREAD

**Issue by smidgeondutchrabbit** [OpenNBS/OpenNoteBlockStudio#453]
open source note block editor huh? this is not open source. if it is "open source" you provide a dmg and exe file. if its just a .exe file, its windows only and windows only is not open source
<img width="1414" alt="Screenshot 2024-05-14 at 4 55 42 PM" src="https://github.com/OpenNBS/OpenNoteBlockStudio/assets/153330282/7b49a9ab-3eb3-4dfe-8276-5eaea4c038a4">
i guess its not "open source" if you cant install it on mac

**Comment by Bentroen** [comment]
Sorry, but that doesn't seem correct! Note Block Studio _**is**_ open-source. The entire source code is available here: https://github.com/OpenNBS/OpenNoteBlockStudio

There's nothing in the OSI's [Definition of Open Source](https://opensource.org/osd) that requires the software in question to be available to any specific platform. There's a variety of open-source programs that are Windows-only — in fact, there's a whole [Wikipedia entry](https://en.wikipedia.org/wiki/Category:Windows-only_free_software) dedicated to them. The platform a program is distributed to has nothing to do with it being open-source. :)

Finally, the reason why Mac distributions aren't available is that there are numerous dependencies which are Windows-only. A lot of work is being made to allow that to happen! Please follow [this discussion](https://github.com/orgs/OpenNBS/discussions/426) for updates, or use this [unofficial fork](https://github.com/time-killer-games/OpenNoteBlockStudio/releases/tag/v0.0.0.0) which has partially-working builds for a variety of platforms.

**Comment by Universum01** [comment]
I think I took brain damage reading what smidgeondutchrabbit  wrote.. lol
