### ISSUE TITLE
i cant sing in

### ISSUE THREAD

**Issue by Bacon4325** [OpenNBS/OpenNoteBlockStudio#469]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Bacon4325** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'sing up'
> 2. Click on 'goggle or github
> 3. Scroll down to 'singed'
> 4. See error still didn't singer even tho I did it 9 time
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

**Comment by Bentroen** [comment]
Sorry, there's not enough information in this report.

The Songs page in the OpenNBS website (https://opennbs.org/songs) has been permanently disabled. This means you can no longer sign up if you haven't created an account before.

And Note Block World (https://noteblock.world/), meant as its replacement, is still on a beta stage -- so only a small selection of users are able to join right now!

If you have any further questions, feel free to leave a comment.
