### ISSUE TITLE
MP3 Export makes instruments sound worse.

### ISSUE THREAD

**Issue by Encode42** [OpenNBS/OpenNoteBlockStudio#77]
When you export your song as MP3, instruments such as the Snare Drum sounds worse than normal. They sound crackly, loud, and sometimes tinny.

1. Open/Create a song in the program
2. Make sure the song has various instruments at once
3. Export the song as MP3 (Default settings)
4. Compare exported MP3 and program quality

The exported MP3 should sound the same as in the program, but it does not.

**Comment by HielkeMinecraft** [comment]
At which version did you first notice this bug?

**Comment by Edude42** [comment]
I've heard this issue before, before ONBS. I can't recall the exact version
number.

**Comment by ShinkoNet** [comment]
It's the bitrate of the exported MP3 file. The snare, with the high frequencies, causes artifacts. I'll see if I can increase the bitrate.
